// components/vue-counter.vue
<script setup>
import { ref, onMounted } from 'vue'

// reactive state
const count = ref(0)

// functions that mutate state and trigger updates
function increment() {
	count.value++
}

// lifecycle hooks
onMounted(() => {
	console.log(`The initial count is ${count.value}.`)
})
</script>

<template>
	<h2> VueJs Counter: {{ count }} </h2>
	<button @click="increment">Increment</button>
</template>

// components/solid-counter.tsx
import { createSignal } from 'solid-js';

const Counter = () => {
	// createSignal is a SolidJS hook that creates a reactive state
	const [count, setCount] = createSignal(0);
	// Function to increment the count
	const increment = () => {
		setCount(count() + 1);
	};

	return (
		<div>
			<h2>SolidJs Counter: {count()}</h2>
			<button onClick={increment}>Increment</button>
		</div>
	);
};

export default Counter;
